flag= --locality
martinaamodt/cockroachdb pull request #43
Opened 2019-10-14 18:36 UTC by joachiwi

added functionality to support the --locality flag

2019-10-14 18:40 UTC, Hexoplon reviewed
Martin jobber allerede med det, se hans pull request

2019-10-14 18:47 UTC, joachiwi commented
japp

2019-10-15 06:56 UTC, Hexoplon requested changes
Fiks logikken i if i service template. Den er snudd, pluss at det burde være and, ikke or

2019-10-15 10:49 UTC, Hexoplon requested changes
<% if $komma == true { -%>,zone=<%= $zone %> <% } -%> <% else { -%> zone=<%= $zone %> <% } -%>
could be:
<% if $komma { -%>, <% } -%>zone=<%= $zone %>

2019-10-15 11:12 UTC, martinaamodt requested changes
Change from $komma to $comma

2019-10-15 11:18 UTC, merged