Fix locality flag
martinaamodt/cockroachdb pull request #83
Opened 2019-10-22 20:25 UTC by Hexoplon

Using $locality as type array

2019-10-22 20:25 UTC, Hexoplon commented
Test with:
```
puppet epp render templates/cockroachdb.service.epp --values '{ node1ip => 'undef',  description => 'undef', workingdirectory => 'undef', node2ip => 'undef', node3ip => 'undef', cache => 'undef', maxsqlmemory => 'undef', timeoutstopsec => 'undef', restart => 'undef', restartsec => 'undef', standardoutput => 'undef', standarderror => 'undef', syslogidentifier => 'undef', user => 'undef', additionalparams => 'undef', locality => ["zone=ciscolab","rack=main","spot=first"] }'
```

2019-10-23 05:43 UTC, martinaamodt requested changes
Fix indentation-issue, then good.

2019-10-23 05:43 UTC, martinaamodt commented on manifests/init.pp
> +  Optional[Array[String, 1]] $locality   = $cockroachdb::params::locality,
Indentation?

2019-10-23 06:32 UTC, martinaamodt approved these changes

2019-10-23 06:32 UTC, merged